## Bernouli Random Variable

In [1]:
import tensorflow_probability as tfp
import tensorflow as tf


In [2]:
keeping_prob = 0.7
r = tfp.distributions.Bernoulli(probs=keeping_prob, dtype=tf.float32).sample(sample_shape=(10, 1))

In [3]:
r

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [4]:
y_prev = tf.random.normal((10, 1))
y_prev

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 0.5753791 ],
       [-0.29427227],
       [-2.0712514 ],
       [ 0.49229527],
       [ 0.8906307 ],
       [ 0.19561787],
       [ 1.3166436 ],
       [-0.97330767],
       [ 0.37950498],
       [-0.521497  ]], dtype=float32)>

In [5]:
y_new = tf.math.multiply(y_prev, r)
y_new

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 0.5753791 ],
       [-0.29427227],
       [-2.0712514 ],
       [ 0.49229527],
       [ 0.8906307 ],
       [ 0.19561787],
       [ 1.3166436 ],
       [-0.97330767],
       [ 0.37950498],
       [-0.521497  ]], dtype=float32)>

## Use Dropout Layer

In [6]:
from tensorflow import keras

In [7]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(10, activation="softmax")
])
model.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])
# n_epochs = 2
# history = model.fit(X_train_scaled, y_train, epochs=n_epochs,
#                     validation_data=(X_valid_scaled, y_valid))

In [8]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dropout (Dropout)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 300)               235500    
                                                                 
 dropout_1 (Dropout)         (None, 300)               0         
                                                                 
 dense_1 (Dense)             (None, 100)               30100     
                                                                 
 dropout_2 (Dropout)         (None, 100)               0         
                                                                 
 dense_2 (Dense)             (None, 10)                1